In [93]:
# simple dataset

data={
    "height":[1.4, 1.2, 1.0, 1.5, 1.8],
    "fav-movie":["baby-days-out", "the original", "pirates of the carrebean", "tom and jerry", "wednesday"]
}

In [94]:
type(data)

dict

In [95]:
import pandas as pd
df = pd.DataFrame(data)
df

   height                 fav-movie
0     1.4             baby-days-out
1     1.2              the original
2     1.0  pirates of the carrebean
3     1.5             tom and jerry
4     1.8                 wednesday

<h1>label encoding</h1>

In [96]:
from sklearn.preprocessing import LabelEncoder

In [97]:
# 1. Sample dataset
#

# 2. Initialize the LabelEncoder
#le = LabelEncoder()

# 3. Fit to the column and transform text to integers
#df['Encoded_Class']=le.fit_transform(df['Target_Class'])
print(df)

   height                 fav-movie
0     1.4             baby-days-out
1     1.2              the original
2     1.0  pirates of the carrebean
3     1.5             tom and jerry
4     1.8                 wednesday

ONE-HOT ENCODING

In [98]:
df_encoded = pd.get_dummies(df,columns=["fav-movie"],dtype="int",drop_first=True)

df_encoded

,height,fav-movie_pirates of the carrebean,fav-movie_the original,fav-movie_tom and jerry,fav-movie_wednesday
0,1.4,0,0,0,0
1,1.2,0,1,0,0
2,1.0,1,0,0,0
3,1.5,0,0,1,0
4,1.8,0,0,0,1

In [99]:
from sklearn.feature_extraction.text import CountVectorizer
data={'reviews':["the food is good",
                 "New food is terrible",
                 "good food and good services"]
    
}

df = pd.DataFrame(data)

vectorizer=CountVectorizer(stop_words='english')

bow_matrix=vectorizer.fit_transform(df['reviews'])

df_bow=pd.DataFrame(bow_matrix.toarray(),columns=vectorizer.get_feature_names_out())

df_bow

   food  good  new  services  terrible
0     1     1    0         0         0
1     1     0    1         0         1
2     1     2    0         1         0

<h1>WORD EMBEDDINGS</h1>

<H2>TOKENIZERS</H2>

<h3>white-space tokenizers</h3>

In [100]:
text = "Deep learning is amazing !"
tokens = text.split()

print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

text = "Deep learning is amazing !"
tokens = text.split("e")

print(tokens)

<h3>word-level tokenization that handles punctuation</h3>

In [101]:
import re

text = "Deep learning is amazing!"
tokens = re.findall(r"\w+|[^\w\s]",text)

print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

<h3>CHARACTER LEVER TOKENIZATION</h3>

In [102]:
character_token = list(text)
print(character_token)

['D', 'e', 'e', 'p', ' ', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', ' ', 'i', 's', ' ', 'a', 'm', 'a', 'z', 'i', 'n', 'g', '!']

In [103]:
with open ("psalms23.txt", "r",encoding="utf-8") as f:
    raw_text = f.read()
len(raw_text), raw_text

(143,
 'The LORD is my shepherd I# 3shall not want \nHe @makes @me lie down in green pastures\nHe leads me ---beside still waters\nHe restores_ my soul\n\n ')

In [104]:
len(raw_text)

143

<h3>TEXT CLEANING USING REGULAR EXPRESSION</h3>

In [105]:
import re
white_space_splitting = re.split(r'\s', raw_text)
print(white_space_splitting)

['The', 'LORD', 'is', 'my', 'shepherd', 'I#', '3shall', 'not', 'want', '', 'He', '@makes', '@me', 'lie', 'down', 'in', 'green', 'pastures', 'He', 'leads', 'me', '---beside', 'still', 'waters', 'He', 'restores_', 'my', 'soul', '', '', '']

In [106]:
#remove @mentions and #tags
raw_text = re.sub(r'@\w+'," ",raw_text,flags=re.MULTILINE)
raw_text = re.sub(r'#\w+'," ",raw_text,flags=re.MULTILINE)

# remove anything that is not alphabet
raw_text = re.sub(r'[^a-zA-Z\s]','',raw_text)

#remove anything whitespace
raw_text = re.sub(r'\s+',' ',raw_text).strip()

raw_text

'The LORD is my shepherd I shall not want He lie down in green pastures He leads me beside still waters He restores my soul'

In [107]:
# splitting using other criteria
white_space_splitting_with_special_xters = re.split(r'--|[@3^!#*?&]|\s', raw_text)
print(white_space_splitting_with_special_xters)

['The', 'LORD', 'is', 'my', 'shepherd', 'I', 'shall', 'not', 'want', 'He', 'lie', 'down', 'in', 'green', 'pastures', 'He', 'leads', 'me', 'beside', 'still', 'waters', 'He', 'restores', 'my', 'soul']

<h3>remove white spaces from the splited text</h3>

In [108]:
strip_text = [word.strip() for word in white_space_splitting_with_special_xters if word.strip()]
len(strip_text)

25

In [109]:
print(strip_text)

['The', 'LORD', 'is', 'my', 'shepherd', 'I', 'shall', 'not', 'want', 'He', 'lie', 'down', 'in', 'green', 'pastures', 'He', 'leads', 'me', 'beside', 'still', 'waters', 'He', 'restores', 'my', 'soul']

<h2>create token-IDs for these words</h2>

In [110]:
#sort the text

sorted_strip_text = sorted(set(strip_text))
print(sorted_strip_text )
#

['He', 'I', 'LORD', 'The', 'beside', 'down', 'green', 'in', 'is', 'leads', 'lie', 'me', 'my', 'not', 'pastures', 'restores', 'shall', 'shepherd', 'soul', 'still', 'want', 'waters']

In [111]:
#enumerates prints 2 
for idx,token in enumerate(sorted_strip_text):
    print(f" {idx} : {token}")

 0 : He
 1 : I
 2 : LORD
 3 : The
 4 : beside
 5 : down
 6 : green
 7 : in
 8 : is
 9 : leads
 10 : lie
 11 : me
 12 : my
 13 : not
 14 : pastures
 15 : restores
 16 : shall
 17 : shepherd
 18 : soul
 19 : still
 20 : want
 21 : waters

In [112]:
# create vocabularies
vocabulary={}
for idx,token in enumerate(sorted_strip_text):
    vocabulary [token] = idx
vocabulary

{'He': 0,
 'I': 1,
 'LORD': 2,
 'The': 3,
 'beside': 4,
 'down': 5,
 'green': 6,
 'in': 7,
 'is': 8,
 'leads': 9,
 'lie': 10,
 'me': 11,
 'my': 12,
 'not': 13,
 'pastures': 14,
 'restores': 15,
 'shall': 16,
 'shepherd': 17,
 'soul': 18,
 'still': 19,
 'want': 20,
 'waters': 21}

In [113]:
# create id-to-string mapping
id_to_str = {}
for idx, token in enumerate(vocabulary):
    print(f" ( {idx} , {token})")

 ( 0 , He)
 ( 1 , I)
 ( 2 , LORD)
 ( 3 , The)
 ( 4 , beside)
 ( 5 , down)
 ( 6 , green)
 ( 7 , in)
 ( 8 , is)
 ( 9 , leads)
 ( 10 , lie)
 ( 11 , me)
 ( 12 , my)
 ( 13 , not)
 ( 14 , pastures)
 ( 15 , restores)
 ( 16 , shall)
 ( 17 , shepherd)
 ( 18 , soul)
 ( 19 , still)
 ( 20 , want)
 ( 21 , waters)

In [114]:
id_to_str = {}
for idx, token in enumerate(vocabulary):
    id_to_str[idx] = token
id_to_str

{0: 'He',
 1: 'I',
 2: 'LORD',
 3: 'The',
 4: 'beside',
 5: 'down',
 6: 'green',
 7: 'in',
 8: 'is',
 9: 'leads',
 10: 'lie',
 11: 'me',
 12: 'my',
 13: 'not',
 14: 'pastures',
 15: 'restores',
 16: 'shall',
 17: 'shepherd',
 18: 'soul',
 19: 'still',
 20: 'want',
 21: 'waters'}

In [115]:
token_ids = [vocabulary[word] for word in strip_text] 
print(token_ids)

[3, 2, 8, 12, 17, 1, 16, 13, 20, 0, 10, 5, 7, 6, 14, 0, 9, 11, 4, 19, 21, 0, 15, 12, 18]

In [116]:
token_recoverd = [id_to_str[idx] for idx in token_ids]
" ".join(token_recoverd)

'The LORD is my shepherd I shall not want He lie down in green pastures He leads me beside still waters He restores my soul'

<h3>class tokenizer</h3>

In [119]:
class tokenizer:
    def _init_(self,vocabulary):
        self.vocabulary = v
        self.id_to_str = {idx:token for idx,token in enumerate(v)}

    def encode(self,text):
        #====Logic
        preprocessed = re.split(r'--|[@^!#*?&]|\s', text)
        preprocessed2 = [w.strip() for w in preprocessed if w.strip() ]
        ids = [self.vocabulary[word] for word in preprocessed2]
        return ids
    def decode(self,ids):
        tokens = [self.id_to_str[idx] for idx in ids]
        return tokens

In [121]:
message ="The Lord is my shepherd i shall not want, he makes me to lie down in green pastures..."
m2 = "i love achu"
tokenizer_ = tokenizer(vocabulary)
tk_ids = tokenizer_.encode(message)
print(tk_ids)

TypeError: tokenizer() takes no arguments